### PR TITLE
Use .sol file to determine whether to read in a solution

### PR DESCRIPTION
**Pull request by JackDunnNZ**
@odow Try this?

### CODE REVIEW

**Comment by JackDunnNZ** [comment]
I should add, it doesn't (yet) deal with the problem of trying to determine the status from whatever message the solver decides to print

**Comment by odow** [comment]
Works great! I guess other than trying to guess some common ones you're never going to be able to support every solver and status...

**Comment by JackDunnNZ** [comment]
I just found the correct way to read in the status, which will at least give the granularity of

    optimal
    infeasible
    unbounded
    limit
    error

I'll merge this and add that soon

**Comment by odow** [comment]
Awesome

**Pull request merged**
