### PR TITLE
Fix String deprecation

### PR DESCRIPTION
**Pull request by odow**

### CODE REVIEW

**Comment by mlubin** [comment]
You don't need the compat macro for AbstractString, it's just a type alias.

**Comment by odow** [comment]
Yeah? It didn't work on my 0.3 otherwise

**Comment by mlubin** [comment]
Did you try this before changing import to using?

**Comment by odow** [comment]
Ahh. My mistake

**Comment by JackDunnNZ** [comment]
Great, thanks!

**Comment by odow** [comment]
No worries. This package is excellent by the way.

**Pull request merged**
